import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [

  route("api/auth/session", "routes/api.auth.session.ts"),
  route("api/auth/logout", "routes/api.auth.logout.ts"),
  route("api/auth/me", "routes/api.auth.me.ts"),
  route("api/s3/presign", "routes/api.s3.presign.ts"),
  route("api/media/presign", "routes/api.media.presign.ts"),
  route("api/users", "routes/api.users.ts"),
  route("api/users/:id", "routes/api.users.$id.ts"),
  route("api/authors", "routes/api.authors.ts"),
  route("api/authors/:id", "routes/api.authors.$id.ts"),
  route("api/portfolio", "routes/api.portfolio.ts"),
  route("api/portfolio/:id", "routes/api.portfolio.$id.ts"),

  route("api/profile", "routes/api.profile.ts"),
  route("api/profile/me", "routes/api.profile.me.ts"),
  route("api/profiles/:slug", "routes/api.profiles.$slug.ts"),
  route("api/blogs", "routes/api.blogs.ts"),
  route("api/blogs/:slug", "routes/api.blogs.$slug.ts"),
  route("api/author/overview", "routes/api.author.overview.ts"),
  route("api/author/blogs", "routes/api.author.blogs.ts"),
  route("api/admin/overview", "routes/api.admin.overview.ts"),
  route("api/admin/health", "routes/api.admin.health.ts"),
  route("api/guestbook", "routes/api.guestbook.ts"),
  route("api/guestbook/:id", "routes/api.guestbook.$id.ts"),
  route("api/notifications", "routes/api.notifications.ts"),
  route("api/notifications/broadcast", "routes/api.notifications.broadcast.ts"),
  route("api/notifications/:id", "routes/api.notifications.$id.ts"),
  route("api/products", "routes/api.products.ts"),
  route("api/products/:slug", "routes/api.products.$slug.ts"),
  route("api/checkout/session", "routes/api.checkout.session.ts"),
  route("api/webhooks/stripe", "routes/api.webhooks.stripe.ts"),
  route("api/orders", "routes/api.orders.ts"),
  route("api/orders/:id", "routes/api.orders.$id.ts"),
  route("api/downloads/recover", "routes/api.downloads.recover.ts"),
  route("api/downloads/:token", "routes/api.downloads.$token.ts"),
  route("api/admin/products", "routes/api.admin.products.ts"),
  route("api/admin/products/:id", "routes/api.admin.products.$id.ts"),
  route("api/admin/orders", "routes/api.admin.orders.ts"),
  route("api/admin/orders/:id", "routes/api.admin.orders.$id.ts"),
  route("api/admin/coupons", "routes/api.admin.coupons.ts"),
  route("login", "routes/login.tsx"),

  layout("routes/_public/_layout.tsx", [
    index("routes/_public/home.tsx"),
    route("blog", "routes/_public/blog.tsx"),
    route("blog/:slug", "routes/_public/blog.$slug.tsx"),
    route("project/:id", "routes/_public/project.$id.tsx"),
    route("author/:slug", "routes/_public/author.$slug.tsx"),
    route("authors/:slug", "routes/_public/authors.$slug.tsx"),
    route("guestbook", "routes/_public/guestbook.tsx"),
  ]),

  layout("routes/_admin/_layout.tsx", [
    route("dashboard", "routes/_admin/dashboard.tsx"),
    route("portfolio-manager", "routes/_admin/portfolio-manager.tsx"),
    route("kanban", "routes/_admin/kanban.tsx"),
    route("applications", "routes/_admin/applications.tsx"),
    route("authors", "routes/_admin/authors.tsx"),
    route("blog-manager", "routes/_admin/blog-manager.tsx"),
    route("companies", "routes/_admin/companies.tsx"),
    route("documents", "routes/_admin/documents.tsx"),
    route("notifications", "routes/_admin/notifications.tsx"),
    route("settings", "routes/_admin/settings.tsx"),
    
    // Coming Soon Routes
   // Coming Soon Routes (each with a unique id)
route("calendar", "routes/_admin/coming-soon.tsx", { id: "routes/_admin/coming-soon-calendar" }),
route("store/products", "routes/_admin/coming-soon.tsx", { id: "routes/_admin/coming-soon-store-products" }),
route("store/orders", "routes/_admin/coming-soon.tsx", { id: "routes/_admin/coming-soon-store-orders" }),
route("store/inventory", "routes/_admin/coming-soon.tsx", { id: "routes/_admin/coming-soon-store-inventory" }),
route("store/coupons", "routes/_admin/coming-soon.tsx", { id: "routes/_admin/coming-soon-store-coupons" }),
route("analytics", "routes/_admin/coming-soon.tsx", { id: "routes/_admin/coming-soon-analytics" }),
route("messages", "routes/_admin/coming-soon.tsx", { id: "routes/_admin/coming-soon-messages" }),
  ]),

  layout("routes/_author/_layout.tsx", [
    route("author/:id/dashboard", "routes/_author/author-dashboard.tsx"),
    route("author/:id/blogs", "routes/_author/blogs.tsx"),
    route("author/:id/profile", "routes/_author/profile.tsx"),
  ]),
] satisfies RouteConfig;
