// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth/session": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/s3/presign": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/projects": {
    params: {};
  };
  "/guestbook": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/portfolio-manager": {
    params: {};
  };
  "/kanban": {
    params: {};
  };
  "/applications": {
    params: {};
  };
  "/authors": {
    params: {};
  };
  "/blog-manager": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/documents": {
    params: {};
  };
  "/author-blogs": {
    params: {};
  };
  "/author-profile": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth/session" | "/api/auth/logout" | "/api/s3/presign" | "/blog" | "/blog/:slug" | "/projects" | "/guestbook" | "/dashboard" | "/portfolio-manager" | "/kanban" | "/applications" | "/authors" | "/blog-manager" | "/companies" | "/documents" | "/author-blogs" | "/author-profile" | "/settings";
  };
  "routes/api.auth.session.ts": {
    id: "routes/api.auth.session";
    page: "/api/auth/session";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "routes/api.s3.presign.ts": {
    id: "routes/api.s3.presign";
    page: "/api/s3/presign";
  };
  "routes/_public/_layout.tsx": {
    id: "routes/_public/_layout";
    page: "/" | "/blog" | "/blog/:slug" | "/projects" | "/guestbook";
  };
  "routes/_public/home.tsx": {
    id: "routes/_public/home";
    page: "/";
  };
  "routes/_public/blog.tsx": {
    id: "routes/_public/blog";
    page: "/blog";
  };
  "routes/_public/blog.$slug.tsx": {
    id: "routes/_public/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/_public/projects.tsx": {
    id: "routes/_public/projects";
    page: "/projects";
  };
  "routes/_public/guestbook.tsx": {
    id: "routes/_public/guestbook";
    page: "/guestbook";
  };
  "routes/_admin/_layout.tsx": {
    id: "routes/_admin/_layout";
    page: "/dashboard" | "/portfolio-manager" | "/kanban" | "/applications" | "/authors" | "/blog-manager" | "/companies" | "/documents";
  };
  "routes/_admin/dashboard.tsx": {
    id: "routes/_admin/dashboard";
    page: "/dashboard";
  };
  "routes/_admin/portfolio-manager.tsx": {
    id: "routes/_admin/portfolio-manager";
    page: "/portfolio-manager";
  };
  "routes/_admin/kanban.tsx": {
    id: "routes/_admin/kanban";
    page: "/kanban";
  };
  "routes/_admin/applications.tsx": {
    id: "routes/_admin/applications";
    page: "/applications";
  };
  "routes/_admin/authors.tsx": {
    id: "routes/_admin/authors";
    page: "/authors";
  };
  "routes/_admin/blog-manager.tsx": {
    id: "routes/_admin/blog-manager";
    page: "/blog-manager";
  };
  "routes/_admin/companies.tsx": {
    id: "routes/_admin/companies";
    page: "/companies";
  };
  "routes/_admin/documents.tsx": {
    id: "routes/_admin/documents";
    page: "/documents";
  };
  "routes/_author/_layout.tsx": {
    id: "routes/_author/_layout";
    page: "/author-blogs" | "/author-profile" | "/settings";
  };
  "routes/_author/blogs.tsx": {
    id: "routes/_author/blogs";
    page: "/author-blogs";
  };
  "routes/_author/profile.tsx": {
    id: "routes/_author/profile";
    page: "/author-profile";
  };
  "routes/_author/settings.tsx": {
    id: "routes/_author/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.auth.session": typeof import("./app/routes/api.auth.session.ts");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.ts");
  "routes/api.s3.presign": typeof import("./app/routes/api.s3.presign.ts");
  "routes/_public/_layout": typeof import("./app/routes/_public/_layout.tsx");
  "routes/_public/home": typeof import("./app/routes/_public/home.tsx");
  "routes/_public/blog": typeof import("./app/routes/_public/blog.tsx");
  "routes/_public/blog.$slug": typeof import("./app/routes/_public/blog.$slug.tsx");
  "routes/_public/projects": typeof import("./app/routes/_public/projects.tsx");
  "routes/_public/guestbook": typeof import("./app/routes/_public/guestbook.tsx");
  "routes/_admin/_layout": typeof import("./app/routes/_admin/_layout.tsx");
  "routes/_admin/dashboard": typeof import("./app/routes/_admin/dashboard.tsx");
  "routes/_admin/portfolio-manager": typeof import("./app/routes/_admin/portfolio-manager.tsx");
  "routes/_admin/kanban": typeof import("./app/routes/_admin/kanban.tsx");
  "routes/_admin/applications": typeof import("./app/routes/_admin/applications.tsx");
  "routes/_admin/authors": typeof import("./app/routes/_admin/authors.tsx");
  "routes/_admin/blog-manager": typeof import("./app/routes/_admin/blog-manager.tsx");
  "routes/_admin/companies": typeof import("./app/routes/_admin/companies.tsx");
  "routes/_admin/documents": typeof import("./app/routes/_admin/documents.tsx");
  "routes/_author/_layout": typeof import("./app/routes/_author/_layout.tsx");
  "routes/_author/blogs": typeof import("./app/routes/_author/blogs.tsx");
  "routes/_author/profile": typeof import("./app/routes/_author/profile.tsx");
  "routes/_author/settings": typeof import("./app/routes/_author/settings.tsx");
};