export const GREETINGS = [
  { greeting: "Hello", language: "English", country: "United States" },
  { greeting: "Bonjour", language: "French", country: "France" },
  { greeting: "Hola", language: "Spanish", country: "Spain" },
  { greeting: "Ciao", language: "Italian", country: "Italy" },
  { greeting: "Hallo", language: "German", country: "Germany" },
  { greeting: "Olá", language: "Portuguese", country: "Portugal" },
  { greeting: "Namaste", language: "Hindi", country: "India" },
  { greeting: "Nǐ hǎo", language: "Mandarin", country: "China" },
  { greeting: "Konnichiwa", language: "Japanese", country: "Japan" },
  { greeting: "Annyeonghaseyo", language: "Korean", country: "South Korea" },
  { greeting: "Marhaba", language: "Arabic", country: "United Arab Emirates" },
  { greeting: "Shalom", language: "Hebrew", country: "Israel" },
  { greeting: "Merhaba", language: "Turkish", country: "Turkey" },
  { greeting: "Salaam", language: "Persian", country: "Iran" },
  { greeting: "Privet", language: "Russian", country: "Russia" },
  { greeting: "Ahoj", language: "Czech", country: "Czech Republic" },
  { greeting: "Cześć", language: "Polish", country: "Poland" },
  { greeting: "Szia", language: "Hungarian", country: "Hungary" },
  { greeting: "Buna", language: "Romanian", country: "Romania" },
  { greeting: "Zdravo", language: "Serbian", country: "Serbia" },
  { greeting: "Geia", language: "Greek", country: "Greece" },
  { greeting: "Hej", language: "Swedish", country: "Sweden" },
  { greeting: "Moi", language: "Finnish", country: "Finland" },
  { greeting: "Hei", language: "Norwegian", country: "Norway" },
  { greeting: "God dag", language: "Danish", country: "Denmark" },
  { greeting: "Dia dhuit", language: "Irish", country: "Ireland" },
  { greeting: "Shwmae", language: "Welsh", country: "Wales" },
  { greeting: "Bula", language: "Fijian", country: "Fiji" },
  { greeting: "Aloha", language: "Hawaiian", country: "United States" },
  { greeting: "Kia ora", language: "Maori", country: "New Zealand" },
  { greeting: "Talofa", language: "Samoan", country: "Samoa" },
  { greeting: "Malo e lelei", language: "Tongan", country: "Tonga" },
  { greeting: "Jambo", language: "Swahili", country: "Kenya" },
  { greeting: "Sawubona", language: "Zulu", country: "South Africa" },
  { greeting: "Dumela", language: "Tswana", country: "Botswana" },
  { greeting: "Salama", language: "Malagasy", country: "Madagascar" },
  { greeting: "Mboté", language: "Lingala", country: "Democratic Republic of the Congo" },
  { greeting: "Sannu", language: "Hausa", country: "Nigeria" },
  { greeting: "Bawo ni", language: "Yoruba", country: "Nigeria" },
  { greeting: "Ndêwó", language: "Igbo", country: "Nigeria" },
  { greeting: "Akwaba", language: "Akan", country: "Ghana" },
  { greeting: "Sabaidi", language: "Lao", country: "Laos" },
  { greeting: "Sawasdee", language: "Thai", country: "Thailand" },
  { greeting: "Mingalaba", language: "Burmese", country: "Myanmar" },
  { greeting: "Suostei", language: "Khmer", country: "Cambodia" },
  { greeting: "Xin chao", language: "Vietnamese", country: "Vietnam" },
  { greeting: "Halo", language: "Indonesian", country: "Indonesia" },
  { greeting: "Kumusta", language: "Tagalog", country: "Philippines" },
  { greeting: "Slamat", language: "Malay", country: "Malaysia" },
  { greeting: "Ayubowan", language: "Sinhalese", country: "Sri Lanka" },
  { greeting: "Vanakkam", language: "Tamil", country: "India" },
  { greeting: "Namaskara", language: "Kannada", country: "India" },
  { greeting: "Namaskaram", language: "Malayalam", country: "India" },
  { greeting: "Nomoshkar", language: "Bengali", country: "India" },
  { greeting: "Kem cho", language: "Gujarati", country: "India" },
  { greeting: "Sat Sri Akal", language: "Punjabi", country: "India" },
  { greeting: "Sain uu", language: "Mongolian", country: "Mongolia" },
  { greeting: "Salam", language: "Azerbaijani", country: "Azerbaijan" },
  { greeting: "Barev", language: "Armenian", country: "Armenia" },
  { greeting: "Gamarjoba", language: "Georgian", country: "Georgia" },
  { greeting: "Salom", language: "Uzbek", country: "Uzbekistan" },
  { greeting: "Sälem", language: "Kazakh", country: "Kazakhstan" },
  { greeting: "Selam", language: "Amharic", country: "Ethiopia" },
  { greeting: "Tariq", language: "Berber", country: "Morocco" },
  { greeting: "Ahalan", language: "Maltese", country: "Malta" },
  { greeting: "Sveiki", language: "Latvian", country: "Latvia" },
  { greeting: "Labas", language: "Lithuanian", country: "Lithuania" },
  { greeting: "Tere", language: "Estonian", country: "Estonia" },
  { greeting: "Góðan dag", language: "Icelandic", country: "Iceland" },
  { greeting: "Përshendetje", language: "Albanian", country: "Albania" },
  { greeting: "Здраво", language: "Macedonian", country: "North Macedonia" },
  { greeting: "Dobar dan", language: "Croatian", country: "Croatia" },
  { greeting: "Kaixo", language: "Basque", country: "Spain" },
  { greeting: "Bongu", language: "Maltese", country: "Malta" },
  { greeting: "Moïen", language: "Luxembourgish", country: "Luxembourg" },
  { greeting: "Grüezi", language: "Swiss German", country: "Switzerland" }
];
