export const BLOG_STATUS = {
  PUBLISHED: 'PUBLISHED',
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
} as const;

export const APPLICATION_STATUS = {
  WISHLIST: 'WISHLIST',
  APPLIED: 'APPLIED',
  HR_SCREENING: 'HR_SCREENING',
  TECHNICAL: 'TECHNICAL',
  OFFER: 'OFFER',
  REJECTED: 'REJECTED',
} as const;
